import os

# =========================
# ??????
# =========================
RUN_MODE = 3
USE_GUI = True
GUI_DELAY_MS = 50
REGENERATE_ROUTES = True
# 场景切换：
#   1 = 三车道直道 + 静态障碍物
#   2 = 0-800m 三车道，800-1200m 两车道，无障碍物
SCENARIO_MODE = 1
# 兼容旧脚本：如需字符串方式，也可以设为 "straight_obstacles" 或 "lane_drop_3_to_2"。
SCENARIO_NAME = None

# ????????
RANDOM_SEED = 3
TRAFFIC_FLOW_PROBABILITY = 0.025
INITIAL_SPEED = 22.0
LANES = (2, 1, 0)
FLOW_GRADIENTS = []
ENABLE_VEHICLE_HETEROGENEITY = False
HOMOGENEOUS_VEHICLE_PARAMS = {
    "max_speed": 30.0,
    "accel": 2.6,
    "decel": 4.5,
    "min_gap": 2.0,
    "tau": 1.2,
    "desired_speed": 24.0,
}

# ?????????
ENABLE_OBSTACLES = True
OBSTACLES = [
    {"id": "obs_0", "lane": 2, "position": 550.0},
    {"id": "obs_1", "lane": 1, "position": 650.0},
    {"id": "obs_2", "lane": 0, "position": 750.0},
]

SUMO_BINARY = None
SUMO_GUI_BINARY = r"C:\Program Files (x86)\Eclipse\Sumo\bin\sumo-gui.exe"

BASE_DIR = os.path.dirname(os.path.dirname(__file__))
NETWORK_DIR = os.path.join(BASE_DIR, "network")
LOG_DIR = os.path.join(BASE_DIR, "logs")
CSV_DIR = os.path.join(BASE_DIR, "csv")
SUMO_CONFIG = os.path.join(NETWORK_DIR, "platoon.sumocfg")
ROUTE_FILE = os.path.join(NETWORK_DIR, "platoon.rou.xml")
OBSTACLE_FILE = os.path.join(NETWORK_DIR, "obstacles.add.xml")

STEP_LENGTH = 0.1
SENSING_RANGE = 50.0
SAFE_DISTANCE = 5.0
SAFE_TIME_HEADWAY = 1.5
STATIC_SAFE_DISTANCE = 8.0
FALLBACK_RELEASE_FACTOR = 1.25
MAX_SPEED = 30.0
MIN_SPEED = 0.0
SIM_END = 600
CRITICAL_DISTANCE = 3.0
OBSTACLE_LOOKAHEAD = 70.0
OBSTACLE_STOP_BUFFER = SAFE_DISTANCE
OBSTACLE_HARD_BRAKE_DISTANCE = 18.0

LANE_CHANGE_DURATION = 2.0
MOBIL_MIN_GAIN = 0.2
MOBIL_BACK_SAFE_GAP = 25.0
MOBIL_FRONT_SAFE_GAP = 45.0
SAFE_LANE_CHANGE_MODE = 1621
YIELD_TO_SIGNAL_DISTANCE = 35.0
YIELD_TO_SIGNAL_DECEL = 0.35
WAITING_SPEED_THRESHOLD = 1.0
WAITING_TIME_TO_FORCE_LANE_CHANGE = 3.0
WAITING_OBSTACLE_DISTANCE = 35.0
WAITING_LANE_CHANGE_COOLDOWN = 0.8
CRUISE_GAIN = 0.35
IDM_DELTA = 4
IDM_TIME_HEADWAY = 1.2

SWARM_ALIGNMENT_GAIN = 0.06
SWARM_COHESION_GAIN = 0.22
SWARM_SEPARATION_GAIN = 0.18
SWARM_MATCH_GAIN = 0.08
SWARM_DESIRED_HEADWAY = 0.85
SWARM_MIN_PLATOON_GAP = 4.5
SWARM_GAP_TOLERANCE = 2.0
SWARM_MAX_ACCEL_DELTA = 0.55
SWARM_MAX_DECEL_DELTA = 0.45
SWARM_MIN_REFERENCE_SPEED = 5.0
SWARM_REFERENCE_SPEED_RATIO = 0.7
SWARM_RECONFIG_LOOKAHEAD = SENSING_RANGE
SWARM_RECONFIG_LOW_SPEED = 4.0
SWARM_RECONFIG_MIN_TARGET_CLEARANCE = 25.0
SWARM_RECONFIG_SPEED_BONUS = 0.35
SWARM_SIGNAL_DELAY = 1.0
SWARM_SIGNAL_MEMORY = 4.0
SWARM_SIGNAL_PREPARE_DECEL = 0.25
LEFT_SIGNAL_BIT = 2
RIGHT_SIGNAL_BIT = 1
SWARM_SLINGSHOT_ENABLE = True
SWARM_SLINGSHOT_REL_SPEED = 1.5
SWARM_SLINGSHOT_MAX_EGO_SPEED = 10.0
SWARM_SLINGSHOT_MIN_GAP = 8.0
SWARM_ZIPPER_ENABLE = True
SWARM_ZIPPER_SIGNAL_DISTANCE = 35.0
SWARM_ZIPPER_YIELD_DELTA = 0.18
SWARM_ZIPPER_ADVANCE_DELTA = 0.16
SWARM_RECONFIG_MOMENTUM_DELTA = SWARM_MAX_ACCEL_DELTA
SWARM_VACANCY_REALLOCATION_ENABLE = True
SWARM_VACANCY_SIGNAL_DISTANCE = 35.0
SWARM_VACANCY_MIN_CLEARANCE = 35.0
SWARM_VACANCY_COOLDOWN = 2.5
SWARM_STAGGER_ENABLE = True
SWARM_STAGGER_GAIN = 0.10
SWARM_STAGGER_HEADWAY = 0.55
SWARM_STAGGER_TOLERANCE = 2.0
SWARM_STAGGER_MAX_DELTA = 0.35
SWARM_STAGGER_CLEAR_OBSTACLE_DISTANCE = 45.0
SWARM_STAGGER_SLOT_GAP = 2.0

RESULTS_FILE = os.path.join(CSV_DIR, "platoon_results.csv")
GUI_SETTINGS_FILE = os.path.join(NETWORK_DIR, "gui-settings.xml")
TRACE_FINISH_POSITION = 1190.0
ROAD_EDGE_ID = "west_to_east"
ROUTE_ID = "r_west_to_east"
LANE_WIDTH = 3.2
NETCONVERT_BINARY = None
LANE_COUNT_FALLBACK = 3
